{
 "title": "Informatics Project",
 "tags": [
  "PI",
  "eBPF",
  "bpftrace"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "System call interface", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "I/O Profile",
   "type": "pcp-flamegraph-panel",
   "description": "Counts stacks on I/O",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "#!/usr/local/bin/bpftrace\n\ntracepoint:syscalls:sys_enter_*read*,\ntracepoint:syscalls:sys_enter_*write*,\ntracepoint:syscalls:sys_enter_*send*,\ntracepoint:syscalls:sys_enter_*recv*\n/$1 == 0 || pid == $1/\n{\n\t@[probe, ustack, comm] = count();\n}"
    }
   ]
  },
  {
   "title": "Syscount - syscalls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "tracepoint:syscalls:sys_enter_*\n{\n    @syscalls[probe] = count()\n}"
    }
   ]
  },
  {
   "title": "Syscount - processes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "#!/usr/bin/env bpftrace\n\ntracepoint:syscalls:sys_enter_*\n{\n\t@process[comm] = count();\n}"
    }
   ]
  },
  { "title": "VFS Layer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Icstat",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "#!/usr/local/bin/bpftrace\n\nBEGIN\n{\n\tprintf(\"Timestamp,REFS,MISSES,HIT%\\n\");\n}\n\nkretprobe:find_inode_fast\n{\n\t@refs++;\n\tif (retval == 0) {\n\t\t@misses++;\n\t}\n}\n\ninterval:s:1\n{\n\t$hits = @refs - @misses;\n\t$percent = @refs > 0 ? 100 * $hits / @refs : 0;\n\tprintf(\"%15s, %10d,%10d,%4d%%\\n\", strftime(\"%H:%M:%S.%f\", nsecs), @refs, @misses, $percent);\n}"
    }
   ]
  },
  {
   "title": "VFS Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "#!/usr/bin/env bpftrace\n\nkprobe:vfs_*\n{\n\t@functions[func] = count();\n}"
    }
   ]
  },
  {
   "title": "FS Layer - XFS Operations latency ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }
  },
  {
   "title": "XFSDist Write",
   "type": "heatmap",
   "description": "Summarize XFS write operation latency",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "#!/usr/bin/env bpftrace\n\nkprobe:xfs_file_write_iter\n{\n\t@start[tid] = nsecs;\n}\n\nkretprobe:xfs_file_write_iter\n/@start[tid]/\n{\n\t@us = hist((nsecs - @start[tid]) / 1000);\n\tdelete(@start[tid]);\n}\n"
    }
   ]
  },
  {
   "title": "XFSDist Open",
   "type": "heatmap",
   "description": "Summarize XFS open operation latency",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "#!/usr/bin/env bpftrace\n\nkprobe:xfs_file_open\n{\n\t@start[tid] = nsecs;\n}\n\nkretprobe:xfs_file_open\n/@start[tid]/\n{\n\t@us = hist((nsecs - @start[tid]) / 1000);\n\tdelete(@start[tid]);\n}"
    }
   ]
  },
  {
   "title": "XFSDist Read",
   "type": "heatmap",
   "description": "Summarize XFS read operation latency",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "#!/usr/bin/env bpftrace\n\nkprobe:xfs_file_read_iter\n{\n\t@start[tid] = nsecs;\n}\n\nkretprobe:xfs_file_read_iter\n/@start[tid]/\n{\n\t@us = hist((nsecs - @start[tid]) / 1000);\n\tdelete(@start[tid]);\n}"
    }
   ]
  },
  {
   "title": "XFSDist Fsync",
   "type": "heatmap",
   "description": "Summarize XFS fsync operation latency",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "#!/usr/bin/env bpftrace\n\nkprobe:xfs_file_fsync\n{\n\t@start[tid] = nsecs;\n}\n\nkretprobe:xfs_file_fsync\n/@start[tid]/\n{\n\t@us = hist((nsecs - @start[tid]) / 1000);\n\tdelete(@start[tid]);\n}"
    }
   ]
  },
  { "title": "Block Device Layer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Block I/O Latency",
   "type": "heatmap",
   "description": "Shows disk I/O Latency as a heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "#!/usr/bin/env bpftrace\n\ntracepoint:block:block_bio_queue\n{\n\t@start[args.sector] = nsecs;\n}\n\ntracepoint:block:block_rq_complete,\ntracepoint:block:block_bio_complete\n/@start[args.sector]/\n{\n\t@usecs = hist((nsecs - @start[args.sector]) / 1000);\n\tdelete(@start[args.sector]);\n}"
    }
   ]
  },
  {
   "title": "Global Bitesize ",
   "type": "heatmap",
   "description": "Shows disk I/O size as a heatmap, global version, i.e, all collapsed into one",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "#!/usr/bin/env bpftrace\n\ntracepoint:block:block_rq_issue\n{\n\t@bytes = hist(args.bytes);\n}"
    }
   ]
  }
 ]
}